// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBETRoyleypIP3q4IsK8L7rfgPslsWZOFY',
    appId: '1:38110982690:web:fb3ec0ca03f2e4c6c8907b',
    messagingSenderId: '38110982690',
    projectId: 'mapy128',
    authDomain: 'mapy128.firebaseapp.com',
    storageBucket: 'mapy128.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPaD-29PLXbUaOWe0wG5fWQT37w9aWkOA',
    appId: '1:38110982690:ios:c24e21b75186e197c8907b',
    messagingSenderId: '38110982690',
    projectId: 'mapy128',
    storageBucket: 'mapy128.firebasestorage.app',
    iosBundleId: 'com.example.mapy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBETRoyleypIP3q4IsK8L7rfgPslsWZOFY',
    appId: '1:38110982690:web:b604f665748b4caac8907b',
    messagingSenderId: '38110982690',
    projectId: 'mapy128',
    authDomain: 'mapy128.firebaseapp.com',
    storageBucket: 'mapy128.firebasestorage.app',
  );
}
